steps:
  - label: 'Audit current licenses'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: license-audit

  - label: ':docker: Build Android gradle plugin CI image'
    key: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          build:
            - android-gradle-plugin-ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest
            - android-gradle-plugin-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-gradle-plugin-ci-v5
      - docker-compose#v3.7.0:
          push:
            - android-gradle-plugin-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-gradle-plugin-ci-v5

  - label: ':android: Detekt'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci
          command: ['./gradlew', 'detekt']

  - label: ':android: Ktlint'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci
          command: ['./gradlew', 'ktlintCheck']

  - label: ':android: Unit tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci
          command: ['./gradlew', 'test']

  - label: ':android: AGP 3.4.0 E2E tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci
          env:
            - AGP_VERSION=7.0.0
            - GRADLE_WRAPPER_VERSION=7.0.2
            - RN_FIXTURE_DIR=features/fixtures/rn065/android
          command: ['bundle', 'exec', 'maze-runner', '-c', '--verbose', '--fail-fast']
